repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        stages: [pre-commit, pre-push]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--explicit-package-bases", "src"]
        pass_filenames: false
        stages: [pre-commit, pre-push]
